---
- name: Ensure network configuration directory exists
  ansible.builtin.file:
    path: /etc/network/interfaces.d
    state: directory
    mode: "0755"

- name: Generate network configuration file
  ansible.builtin.template:
    src: network_config.j2
    dest: "{{ network_interfaces_file }}"
    mode: "0644"
    backup: true
  notify: Restart Networking
