---
wrt_ssh_on_wan: true
wrt_http_on_wan: true
wrt_lan_ipaddr: "10.63.10.1"
wrt_ssh_port: "22"
wrt_ntp_server:
  - "0.openwrt.pool.ntp.org"
  - "1.openwrt.pool.ntp.org"
  - "2.openwrt.pool.ntp.org"
  - "3.openwrt.pool.ntp.org"
