auth_enabled: false
server:
  http_listen_address: 127.0.0.1
  grpc_listen_address: 127.0.0.1
  http_listen_port: 3100
  grpc_listen_port: 9096
  grpc_server_max_concurrent_streams: 1000


ingester:
  chunk_target_size: 1048576
  max_chunk_age: 1h
  chunk_idle_period: 5m
  wal:
    dir: /loki/wal
  lifecycler:
    ring:
      kvstore:
        store: inmemory
      replication_factor: 1
    final_sleep: 0s



storage_config:
  tsdb_shipper:
    active_index_directory: /loki/index  # Set the active index directory
    cache_location: /loki/cache  # Set the cache location
  filesystem:
    directory: /loki/chunks


compactor:
  working_directory: /loki/compactor

query_range:
  results_cache:
    cache:
      embedded_cache:
        enabled: true
        max_size_mb: 100


limits_config:
  metric_aggregation_enabled: true
  enable_multi_variant_queries: true
  reject_old_samples: true
  reject_old_samples_max_age: 168h
  allow_structured_metadata: false

schema_config:
  configs:
    - from: 2020-10-24
      store: tsdb
      object_store: filesystem
      schema: v13
      index:
        prefix: index_
        period: 24h

pattern_ingester:
  enabled: true
  metric_aggregation:
    loki_address: localhost:3100

ruler:
  alertmanager_url: http://localhost:9093

frontend:
  encoding: protobuf


table_manager:
  retention_deletes_enabled: true
  retention_period: 7d
