---
# OPNsense network configuration variables
network_config_opnsense_lan_ip: 10.68.0.1
network_config_opnsense_lan_netmask: 24
network_config_opnsense_wan_ip: 138.201.133.113
network_config_opnsense_wan_netmask: 26
network_config_opnsense_additional_ips:
  - 138.201.133.94
  - 138.201.133.98
  - 138.201.133.99