---
proxmox_vmid: 101

ansible_user: root
ansible_ssh_transfer_method: sftp
ansible_ssh_use_tty: false
ansible_scp_if_ssh: true
ansible_remote_tmp: "/tmp"
ansible_python_interpreter: ""

openwrt_install_recommended_packages: false

dns_inwx:
  - domain: rackmonkey.de
    type: A
    record: fw
    value: 138.201.133.94

wrt_ssh_allow_on_wan: true
wrt_luci_allow_on_wan: true

wrt_interface:
  - name: wan
    proto: dhcp
    device: eth1
  - name: lan
    proto: static
    device: eth0
    ipaddr: 10.63.10.1
    netmask: '255.255.255.0'

wrt_ntp_server:
  - '0.openwrt.pool.ntp.org'
  - '1.openwrt.pool.ntp.org'
  - '2.openwrt.pool.ntp.org'
  - '3.openwrt.pool.ntp.org'

# wrt_redirect:
#   - dest: 'lan'
#     target: 'DNAT'
#     name: 'ssh git.rackmonkey.de'
#     src: 'wan'
#     src_dport: '30130'
#     dest_ip: '10.63.10.6'
#     dest_port: '22'

wrt_ssh_on_wan: true
wrt_http_on_wan: true
