---
ansible_python_interpreter: ""
ansible_remote_tmp: /tmp
ansible_scp_if_ssh: true
ansible_ssh_transfer_method: sftp
ansible_ssh_use_tty: false
ansible_user: root
dns_inwx:
  - domain: rackmonkey.de
    record: fw
    type: A
    value: 138.201.133.94
openwrt_install_recommended_packages: false
proxmox_vmid: 101
wrt_http_on_wan: true
wrt_interface:
  - device: eth1
    name: wan
    proto: dhcp
  - device: eth0
    ipaddr: 10.63.10.1
    name: lan
    netmask: 255.255.255.0
    proto: static
wrt_luci_allow_on_wan: true
wrt_ntp_server:
  - 0.openwrt.pool.ntp.org
  - 1.openwrt.pool.ntp.org
  - 2.openwrt.pool.ntp.org
  - 3.openwrt.pool.ntp.org
wrt_ssh_allow_on_wan: true
# wrt_redirect:
#   - dest: 'lan'
#     target: 'DNAT'
#     name: 'ssh git.rackmonkey.de'
#     src: 'wan'
#     src_dport: '30130'
#     dest_ip: '10.63.10.6'
#     dest_port: '22'
wrt_ssh_on_wan: true
