---
dns_inwx:
  # Bastelfreak altlasten
  - domain: rackmonkey.de
    record: webserver01
    type: A
    value: 144.76.249.219
  - domain: rackmonkey.de
    record: webserver01
    type: AAAA
    value: 2a01:4f8:171:1152::4
  - domain: rackmonkey.de
    record: mail01
    type: A
    value: 144.76.249.221
  - domain: rackmonkey.de
    record: mail01
    type: AAAA
    value: 2a01:4f8:171:1152::7
