---
proxmox_vmid: 101

dns_inwx:
  - domain: rackmonkey.de
    type: A
    record: fw
    value: 138.201.133.94

wrt_ssh_allow_on_wan: true
wrt_luci_allow_on_wan: true

wrt_interface:
  - name: wan
    proto: dhcp
    device: eth1
  - name: lan
    proto: static
    device: eth0
    ipaddr: 10.63.10.1
    network: '255.255.255.0'

wrt_ntp_server:
  - '0.openwrt.pool.ntp.org'
  - '1.openwrt.pool.ntp.org'
  - '2.openwrt.pool.ntp.org'
  - '3.openwrt.pool.ntp.org'


wrt_redirect_ssh:
  subnet_prefix: "10.63.10."
  from: 2
  to: 255
  base_port: 30100

wrt_redirect:
  dest: 'lan'
  target: 'DNAT'
  name: 'ssh git.rackmonkey.de'
  src: 'wan'
  src_dport: '30100'
  dest_ip: '10.63.10.2'
  dest_port: '22'
