---
dns_inwx:
  - domain: int.rackmonkey.de
    record: monitoring
    type: A
    value: 10.63.13.3

dns_inwx_cname:
  - domain: rackmonkey.de
    records:
      - monitoring
      - alertmanager
      - prometheus
      - loki
      - grafana
    type: CNAME
    value: proxy.rackmonkey.de
  - domain: int.rackmonkey.de
    records:
      - alertmanager
      - prometheus
      - loki
      - grafana
    type: CNAME
    value: monitoring.int.rackmonkey.de


haproxy_services:
  - name: monitoring.rackmonkey.de
    IP: 10.63.13.3
    Port: 8000
  - name: prometheus.rackmonkey.de
    IP: 10.63.13.3
    Port: 9090
  - name: loki.rackmonkey.de
    IP: 10.63.13.3
    Port: 3100
  - name: alertmanager.rackmonkey.de
    IP: 10.63.13.3
    Port: 9093

