---
postgres: true # marker to install posgres
postgres_listen_addresses: "*"
postgres_port: 5432

postgres_users:
  - name: keycloak
    password: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          38356238653439333232303361396564366564626231313465333961376232376166376166636137
          6536353638656466366665323965303363373335666436390a383862373832663934636333353232
          37346232356439323564336638346165343362636239323362366535323666376665373764663830
          3338626439316539630a326262373062373762363032343431386663363439353934373836303330
          35633166666434616131363135656466663133373334313036313463363832313163336365313937
          62643937323763366261663733303130613339366633376535366234333063653466323937393333
          623433383336663739396138666539333739

postgres_databases:
  - name: keycloak
    owner: keycloak

postgres_hba_rules:
  - type: host
    database: keycloak
    user: keycloak
    address: 10.63.13.0/24
    method: scram-sha-256

dns_inwx_cname:
  - domain: rackmonkey.de
    records:
      - pg
    type: CNAME
    value: proxy.rackmonkey.de

dns_inwx:
  - domain: int.rackmonkey.de
    record: pg
    type: A
    value: 10.63.13.5