---


lego_certs:
  - domains:
      - proxy.rackmonkey.de
  - domains:
      - test.rackmonkey.de
dns_inwx_cname:
  - domain: rackmonkey.de
    records:
      - proxy
    type: A
    value: 138.201.133.94
