---
proxmox_vmid: 102

network_interfaces_interfaces:
  - name: eth0
    address: 10.63.10.3
    netmask: 255.255.255.0
    gateway: 10.63.10.1
    nat_subnet: rackmonkey

dns_inwx_cname:
  - domain: rackmonkey.de
    type: CNAME
    records:
      - proxy
    value: fw.rackmonkey.de


certbot_install_method: "pip"
certbot_certs:
  - domains: [proxy.rackmonkey.de]

nginx_proxy_deployment: "package"
nginx_proxy:
  - target_fqdn: fw.rackmonkey.de
    src_address: 10.63.10.1
    src_port: 80
    proxy_ssl: false
  - target_fqdn: git.rackmonkey.de
    src_address: 10.63.10.3
    src_port: 80
    proxy_ssl: false

nginx_proxy_dns_resolver: 192.168.1.2
