---
dns_inwx:
  - domain: rackmonkey.de
    record: pve
    type: A
    value: 138.201.133.113
network_interfaces_interfaces:
  - address: 138.201.133.113/32
    bridge_fd: 0
    bridge_ports: enp0s31f6
    bridge_stp: off
    comment: uplink bridge
    gateway: 138.201.133.65
    mode: static
    name: bridge-uplink
    ports: enp0s31f6
  - address: 2a01:4f8:172:30ad::1/64
    mode: static
    name: bridge-uplink
    protocol: inet6
    gateway: fe80::1
  - address: 10.63.13.1/24
    bridge: true
    bridge_fd: 0
    bridge_ports: none
    bridge_stp: off
    comment: bridge internal for shared services
    mode: static
    name: bridge-internal
