---
keycloak: true # marker to install keycloak
keycloak_hostname: https://sso.rackmonkey.de

keycloak_db_host: pg.int.rackmonkey.de
keycloak_db_port: 5432
keycloak_db_name: keycloak
keycloak_db_user: keycloak
keycloak_db_password: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          38356238653439333232303361396564366564626231313465333961376232376166376166636137
          6536353638656466366665323965303363373335666436390a383862373832663934636333353232
          37346232356439323564336638346165343362636239323362366535323666376665373764663830
          3338626439316539630a326262373062373762363032343431386663363439353934373836303330
          35633166666434616131363135656466663133373334313036313463363832313163336365313937
          62643937323763366261663733303130613339366633376535366234333063653466323937393333
          623433383336663739396138666539333739

keycloak_admin_user: admin
keycloak_admin_password: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          61373330353162636636316138303366616364656431383532333637643532333061323835666138
          3635656636373861656162626662373862626662373239300a323763383530353133343030336265
          32363763616466333666643931363630643564316166666562343865663831393230613235663739
          3137623865323165610a636530353632613533643931333266393838633265613863383038393962
          36376366663338666134353835383431666234393738343266313165616632613031383438353964
          62626264643835613631316636306431393931663431626562633262306133643432666164353635
          666434303936653734663432353362616437

dns_inwx_cname:
  - domain: rackmonkey.de
    records:
      - sso
    type: CNAME
    value: proxy.rackmonkey.de

dns_inwx:
  - domain: int.rackmonkey.de
    record: sso
    type: A
    value: 10.63.13.4

haproxy_services:
  - name: sso.rackmonkey.de
    IP: 10.63.13.4
    Port: 8080