---
keycloak: true # marker to install keycloak
keycloak_hostname: https://sso.rackmonkey.de

keycloak_db_host: pg.int.rackmonkey.de
keycloak_db_port: 5432
keycloak_db_name: keycloak
keycloak_db_user: keycloak
keycloak_db_password: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          38356238653439333232303361396564366564626231313465333961376232376166376166636137
          6536353638656466366665323965303363373335666436390a383862373832663934636333353232
          37346232356439323564336638346165343362636239323362366535323666376665373764663830
          3338626439316539630a326262373062373762363032343431386663363439353934373836303330
          35633166666434616131363135656466663133373334313036313463363832313163336365313937
          62643937323763366261663733303130613339366633376535366234333063653466323937393333
          623433383336663739396138666539333739

keycloak_intial_admin_user: admin
keycloak_intial_admin_password: &kc_admin_pw !vault |
  $ANSIBLE_VAULT;1.1;AES256
  31623739653866623762663031333532386537363836626536623166363163663334313936346661
  6236343666373130633739396437323233316366356333620a373932306664616163643066333839
  63646366666662646430363665656538313830393730303666313531343636303135653830303962
  6434616633363134370a366361383961363837656531626431633534353635653536663932353639
  30353266353034333935333232636632333163663362386130663232643638373962653262636239
  62613230623664663365303965653664363533663636316131383637626537666465303465346532
  323236653465326334373162366564356630

keycloak_admin_user: master-admin
keycloak_admin_password: !vault |
  $ANSIBLE_VAULT;1.1;AES256
  65323032376564353235613431323633333636323961346561633164616131366430393863353138
  3463646137633337313364383632646362656264393562360a643534386431343731383534646461
  31323938366363383661643135633766366438366466363064356439336462626432333433326464
  3566386339666535620a393834373364653461666334616631306538373436333866316664373364
  61393466303736326633393033373934343565383231643461313833366666346435

keycloak_manage_auth_keycloak_url: "https://sso.rackmonkey.de"
keycloak_manage_auth_username: master-admin
keycloak_manage_auth_password: !vault |
  $ANSIBLE_VAULT;1.1;AES256
  31626530396636643239653938653632366132656463323535646666633963313764626365386565
  3137623336326537393366396439663832376433313762390a383261316236313030363361646131
  64343936346535643231386162373464323164353164333431313636656263326664336264346132
  6536643232396534380a663266626238653434643030366461633632323464383266393366383035
  66333237396662323535653932306363343235393031343139313936646461343032
keycloak_manage_auth_secret: !vault |
  $ANSIBLE_VAULT;1.1;AES256
  32346230373366656530396463646432313565333666616131323762646365663937366461653830
  3636306165316133363365396631396434316239393566650a613265623065616135326432356531
  65646463303931346639383438343332343936643236613634626565653039633030663437313538
  3436303330316630320a613437383561326238623939376262343032663933386161303132373361
  36646435386232336562316236613831343239653235353137396334376136346338616532396438
  6237653239353436336361656639363961656433613663356339

keycloak_manage_realms:
  - name: rackmonkey
    enabled: true
    state: present

dns_inwx_cname:
  - domain: rackmonkey.de
    records:
      - sso
    type: CNAME
    value: proxy.rackmonkey.de

dns_inwx:
  - domain: int.rackmonkey.de
    record: sso
    type: A
    value: 10.63.13.4

haproxy_services:
  - name: sso.rackmonkey.de
    IP: 10.63.13.4
    Port: 8080