---
- name: Install packages
  ansible.builtin.package:
    name:
      - haproxy
      - lego
      - python3-cryptography
    state: present
    update_cache: true

- name: Ensure haproxy cert directory exists
  ansible.builtin.file:
    path: "{{ haproxy_cert_path }}"
    state: directory
    owner: root
    group: root
    mode: "0755"

- name: Create haproxy_all_services fact
  ansible.builtin.set_fact:
    haproxy_all_services: >-
      {{ haproxy_all_services | default([]) +
          (hostvars[item].haproxy_services | default([])) }}
  loop: "{{ groups['all'] }}"

- name: Show aggregated services
  ansible.builtin.debug:
    var: haproxy_all_services


- name: Template Haproxy Config
  ansible.builtin.template:
    src: haproxy.cfg
    dest: /etc/haproxy/haproxy.cfg
    owner: root
    group: root
    mode: "0644"
  notify:
    - Reload HAProxy

- name: Generate a dummy self-signed cert only if none exist
  ansible.builtin.command: >
    openssl req -x509 -nodes -days 365 -newkey rsa:2048
    -keyout {{ haproxy_cert_path }}/selfsigned-default.com.pem
    -out {{ haproxy_cert_path }}/selfsigned-default.com.pem
    -subj "/CN=dummy-default.com"
  args:
    creates: "{{ haproxy_cert_path }}/selfsigned-default.com.pem"
  become: true

- name: Ensure Haproxy service is running and enabled
  ansible.builtin.systemd:
    name: haproxy
    state: started
    enabled: true

- name: Include lego tasks
  ansible.builtin.import_tasks: lego.yaml
