$ANSIBLE_VAULT;1.1;AES256
65663730356566366331393265623762343161643635376465366233353937303033633231306564
3335343535383465363561356635636239333264656637370a643066366464633639333233306461
63363737653362326663323636373038353333346431336238653530366232373233666634373534
3736393432376439370a336664313962363764653335653866306664303066306430636637343232
30666132383733313234366134333332643736616131303739613337333763303135353964353161
65343963663937333134613463333330623630383830356435373734383832353364343161613432
31663338306635383165386233653462393963386430373564613632303637323966386432636535
66653031653664653539666634346165666139316334313234373838303838386533313661306666
61663635316430333965333130663464383066373765653838633437353332633064336162306564
30373161643066646462396536653933303530323565383933356235353833383162376235623432
31626636306538626663633236663132613063303731373337376561663463373337383130383161
38386138303030316337363262663039396532373331316630663366626561366439336239303262
39653934353662386363343339346430303063633639356533333730333635653732383934626138
34373065336130386663633237336236646262653932623861313238636433663539636536353037
63346238353365646631343835396233643664346234323331633261363466393935656663666266
34646164663733376465
