---
ansible_user: ansible
atuin_checksum: sha256:21fd614adca7bb6e26b7e37d867b7a8ff3436df8821e74de3941bc18533b1898
atuin_dl_link: https://github.com/atuinsh/atuin/releases/download/v18.10.0/atuin-x86_64-unknown-linux-gnu.tar.gz
atuin_version_string: atuin 18.10.0
dns_inwx_managed_domains:
  - rackmonkey.de
  - int.rackmonkey.de
dns_inwx_zone_ignore_subdomains:
  - home
user_sudo_without_password: true
user_zsh: true
users:
  - authorized_keys:
      - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAILZIcGOqCoTrLbCg06e3HYHwweskvvdPK+w81LlHmHvM debauer@bauer-t14s
      - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIDwzwboGpAFHjhezJWFu/I3ERf2mWMQYMc/4N8yn9h1l
      - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIPCmpZ0IZG91e4q6+c0jtgJ62JvE8JbumXLRtpp86/yv
    groups:
      - wheel
    name: ansible
    shell: /bin/sh
    ssh: true
  - authorized_keys:
      - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAILZIcGOqCoTrLbCg06e3HYHwweskvvdPK+w81LlHmHvM debauer@bauer-t14s
    groups:
      - wheel
    name: debauer
    shell: /bin/zsh
    ssh: true
  - authorized_keys:
      - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIDwzwboGpAFHjhezJWFu/I3ERf2mWMQYMc/4N8yn9h1l
      - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIPCmpZ0IZG91e4q6+c0jtgJ62JvE8JbumXLRtpp86/yv
    groups:
      - wheel
    name: korkenzieher
    shell: /bin/zsh
    ssh: true

pve_bridge:
  br-uplink:
    public: true
    networks:
      - 138.201.133.94/32
      - 138.201.133.98/32
      - 138.201.133.99/32
  br-internal:
    public: false
    proxy: proxy.rackmonkey.de
    networks:
      - 10.63.13.0/24

ansible_python_interpreter: /usr/bin/python3

ssh_basic_port_debug: true
ssh_basic_proxy_host: proxy.rackmonkey.de
ssh_basic_proxy_port: 1022