---
# Default network configuration variables
network_interfaces_file: /etc/network/interfaces_test
network_interfaces_dns_servers: ["1.1.1.1", "8.8.8.8"]
network_interfaces_interfaces:
  - name: vmbr0
    ip: 138.201.133.113
    netmask: 255.255.255.255
    ports: enp0s31f6
    gateway: 138.201.133.65
  - name: vmbr1
    ip: 10.63.0.2
    netmask: 255.255.255.0
    ports: none
    gateway: 138.201.133.65
