---
- name: Ensure snapd is installed.
  ansible.builtin.package:
    name: snapd
    state: present
  register: certbot_inwx_snapd_install

- name: Ensure snapd is enabled.
  ansible.builtin.systemd:
    name: snapd.socket
    enabled: true
    state: started

- name: Enable classic snap support.
  ansible.builtin.file:
    src: /var/lib/snapd/snap
    dest: /snap
    state: link
  when: ansible_os_family != "Debian"

- name: Update snap after install.
  ansible.builtin.shell: snap install core; snap refresh core
  changed_when: true
  failed_when: false
  when: certbot_inwx_snapd_install is changed  # noqa: no-handler

- name: Install certbot via snap.
  community.general.snap:
    name: certbot
    classic: true

- name: Symlink certbot into place.
  ansible.builtin.file:
    src: /snap/bin/certbot
    dest: /usr/bin/certbot
    state: link
  ignore_errors: "{{ ansible_check_mode }}"

- name: Set Certbot script variable.
  ansible.builtin.set_fact:
    certbot_script: /usr/bin/certbot  # noqa: var-naming[no-role-prefix]

- name: Install certbot-dns-inwx via snap.
  community.general.snap:
    name: certbot-dns-inwx

- name: Snap set certbot trust-plugin-with-root=ok
  ansible.builtin.command: "snap set certbot trust-plugin-with-root=ok"
  changed_when: false

- name: Snap connect certbot:plugin certbot-dns-inwx
  ansible.builtin.command: "snap connect certbot:plugin certbot-dns-inwx"
  changed_when: false

- name: Snap connect certbot-dns-inwx:certbot-metadata certbot:certbot-metadata
  ansible.builtin.command: "snap connect certbot-dns-inwx:certbot-metadata certbot:certbot-metadata"
  changed_when: false
