---
packages_common:
  - sudo # proxmox hat kein sudo :-(
  - make
  - wget
  - gzip
  - tree
  - net-tools
  - vim
  - rsyslog
  - curl
  - dnsutils
  - etckeeper
  - git
  - htop
  - iftop
  - iotop
  - less
  - libpam-systemd
  - lsof
  - mtr-tiny
  - multitail
  - ncdu
  - rsync
  - tig
  - tmux
  - unzip

packages_additional: []
packages_remove: []
packages_pip_install: false

packages_pip_for_users: []
packages_pip_for_user_additional: []
packages_pip_for_root: []
packages_pip_for_root_additional: []
