---
- name: Resolve SSH access for Proxmox guests
  hosts: all,!meta
  gather_facts: false
  connection: local
  tags:
    - always

  tasks:
    - name: Include role to set correct ssh proxy
      ansible.builtin.include_role:
        name: roles/basic/basic_ssh
      tags:
        - always
