## enable or disable automatic sync
auto_sync = false
update_check = false
invert = false
inline_height = 20
enter_accept = true

## possible values: auto, full, compact
style = "compact"

db_path = "~/.history.db"
search_mode = "fuzzy"

## prevent commands matching any of these regexes from being written to history.
## Note that these regular expressions are unanchored, i.e. if they don't start
## with ^ or end with $, they'll match anywhere in the command.
## For details on the supported regular expression syntax, see
## https://docs.rs/regex/latest/regex/#syntax
# history_filter = [
#   "^secret-cmd",
#   "^innocuous-cmd .*--secret=.+",
# ]