---
prometheus_repo: prometheus/prometheus
prometheus_version: latest

prometheus_user: prometheus
prometheus_group: prometheus
prometheus_create_user: true

prometheus_install_dir: /opt/prometheus
prometheus_bin_dir: /usr/local/bin
prometheus_config_dir: /etc/prometheus
prometheus_data_dir: /var/lib/prometheus

prometheus_service_name: prometheus
prometheus_web_listen_address: 0.0.0.0:9090
prometheus_storage_retention_time: 15d
prometheus_extra_args: []

prometheus_arch_map:
  x86_64: amd64
  amd64: amd64
  aarch64: arm64
  arm64: arm64
