---
- name: Update inwx dns
  hosts: inwx
  gather_facts: false

  tasks:
    - name: Include dns_inwx role
      ansible.builtin.include_role:
        name: roles/dns_inwx
      delegate_to: localhost
