---
- name: Configure Reverse Proxy for Rackmonkey
  hosts: proxy.rackmonkey.de
  gather_facts: true
  become: true
  tasks:
    - name: Include role
      ansible.builtin.include_role:
        name: roles/haproxy
    # - name: Include role
    #   ansible.builtin.include_role:
    #     name: roles/lego

