---
- name: Package - Install nginx
  ansible.builtin.package:
    name: [nginx]

- name: Package - Enable service httpd and ensure it is not masked
  ansible.builtin.systemd:
    name: nginx
    enabled: true

- name: Package - Copy nginx.conf to server
  ansible.builtin.template:
    src: nginx.conf
    dest: "{{ nginx_proxy_deployment_path }}/nginx.conf"
    owner: root
    group: root
    mode: "0644"
  become: true
  notify: Nginx restart
