---
ansible_user: ansible
atuin_checksum: sha256:21fd614adca7bb6e26b7e37d867b7a8ff3436df8821e74de3941bc18533b1898
atuin_dl_link: https://github.com/atuinsh/atuin/releases/download/v18.10.0/atuin-x86_64-unknown-linux-gnu.tar.gz
atuin_version_string: atuin 18.10.0
dns_inwx_managed_domains:
  - rackmonkey.de
dns_inwx_zone_ignore_subdomains:
  - home
